---
replacers:
  - search: "/- (feat|fix|docs|chore|cleanup|style|refactor|perf|test)(\\([^) ]+\\))?: /g"
    replace: "- "

name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

autolabeler:
  - label: enhancement
    title: '/^feat[:(]/'
  - label: bug
    title: '/^fix[:(]/'
  - label: documentation
    title: '/^docs[:(]/'
  - label: chore
    title: '/^chore[:(]/'
  - label: cleanup
    title: '/^cleanup[:(]/'
  - label: style
    title: '/^style[:(]/'
  - label: refactor
    title: '/^refactor[:(]/'
  - label: performance
    title: '/^perf[:(]/'
  - label: test
    title: '/^test[:(]/'

categories:
  - title: "Breaking changes"
    labels:
      - api break
  - title: "Features"
    labels:
      - enhancement
  - title: "Performance improvements"
    labels:
      - performance
  - title: "Bug Fixes"
    labels:
      - bug
  - title: "Documentation"
    labels:
      - documentation
  - title: "Maintenance (Grunt tasks)"
    labels:
      - chore
  - title: "Maintenance (Code cleanup)"
    labels:
      - cleanup
  - title: "Maintenance (Dependencies)"
    labels:
      - dependencies
  - title: "Maintenance (Refactoring)"
    labels:
      - refactor
  - title: "Maintenance (Tests)"
    labels:
      - test
  - title: "Maintenance (Code style)"
    labels:
      - style

template: |
  ## Release Notes

  $CHANGES
